---
kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: "src/github.com/blake/external-mdns"

platform:
  os: linux

steps:
  - name: build
    image: golang:1.16
    commands:
      - go vet ./...
      - env GOARCH=amd64 sh -c 'go build -ldflags="-s -w" -o build/$(printf "external-mdns_%s_%s" $GOOS $GOARCH) .'
      - env GOARCH=arm64 sh -c 'go build -ldflags="-s -w" -o build/$(printf "external-mdns_%s_%s" $GOOS $GOARCH) .'
    environment:
      CGO_ENABLED: "0"
      GOOS: "${DRONE_STAGE_OS:-linux}"

---
kind: signature
hmac: a3a8ed0182bd107e85f002ccb73a1bb1475d4076eee658ee1fe5ba27c9583d1b
